# This docker-compose file is used to run the project's published image
#
# Usage: docker-compose up [-d]
#
# See comment in docker-compose.dev.yml if you want to run for development.

version: '3.4'

networks:
  opencommerce:
    external:
      name: opencommerce.localhost

services:
  web:
    image: mailchimp-open-commerce/example-storefront:4.0.1
    env_file:
      - ./.env
    networks:
      default:
      opencommerce:
    ports:
      - 4000:4000
